// <auto-generated />
using System;
using DataSource.VassCommerceDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace vassCommerce.Migrations
{
    [DbContext(typeof(VassCommerceDbContext))]
    [Migration("20250903165431_AddEnderecoModel")]
    partial class AddEnderecoModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Models.ClienteModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Models.ClienteModel", b =>
                {
                    b.OwnsOne("EnderecoModel", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("ClienteModelId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Complemento")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DataCadastro")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DataUltimaAtualizacao")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Numero")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Rua")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Telefone")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ClienteModelId");

                            b1.ToTable("Endereco");

                            b1.WithOwner()
                                .HasForeignKey("ClienteModelId");
                        });

                    b.Navigation("Endereco")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
